# Generated by Django 5.0.4 on 2024-05-08 06:11

from django.contrib.gis.db import models
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
                ('geom', models.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
